# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_page_is_recomend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
