# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_page_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_publick',
            field=models.BooleanField(default=False),
        ),
    ]
