# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171114_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
