# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171006_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='flavor_text',
        ),
    ]
