# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171016_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
