# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171019_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
