# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171019_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Cocktails',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Tasting_note',
            field=models.TextField(null=True),
        ),
    ]
