# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171022_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_text',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.EmailField(blank=True, max_length=75, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=15, null=True, verbose_name='氏名'),
        ),
    ]
