# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Page',
        ),
    ]
