# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171107_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
