# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171107_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='keywords',
        ),
    ]
