# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_page_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
