# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_botanicals_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Botanical',
        ),
        migrations.AddField(
            model_name='post',
            name='history',
            field=models.TextField(default='comming soon', null=True),
        ),
    ]
