# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171129_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(1, 'ドライジン'), (2, 'ジュネヴァ'), (3, 'シュタインヘーガー'), (4, 'オールド・トム・ジン'), (5, 'スロージン'), (6, 'その他')], null=True, verbose_name='ジャンル'),
        ),
    ]
