# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20171206_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
                ('content', models.TextField(default='comming soon', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
