# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20171206_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
