# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='settings.STATIC_ROOT/photo/404.png', upload_to='document/'),
        ),
    ]
