# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20171208_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/document/404.png', upload_to='document/'),
        ),
    ]
